# Generated by Django 3.2.16 on 2023-05-23 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do medicamento', max_length=100, verbose_name='Nome')),
                ('dosagem', models.CharField(help_text='Ex. 40MG/mL AMP/2mL', max_length=100, verbose_name='Dosagem')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do paciente', max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(help_text='Digite a idade', null=True, verbose_name='Idade')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Inicio do tratamento')),
                ('data_fim', models.DateField(verbose_name='Fim do tratamento')),
                ('quantidade_dia', models.IntegerField(blank=True, help_text='Quantidade a ser tomada por dia', null=True, verbose_name='Quantidade(Dia)')),
                ('horario', models.CharField(help_text='Ex. 8/8, 6/6', max_length=10, verbose_name='Horário')),
                ('status', models.CharField(choices=[('Em Tratamento', 'Em Tratamento'), ('Encerrado', 'Encerrado')], default='Em Tratamento', max_length=20)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='core.medicamento', verbose_name='Medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Tratamento',
                'verbose_name_plural': 'Tratamentos',
            },
        ),
    ]
